scalo/reservas/urls.py
from django.urls import path
from reservas import views, reservas, predio, estadisticas,email


urlpatterns = [
    #INDEX
    path('',views.index,name='index'),

    #LOGIN
    path('login',         views.login_view,   name = 'login'),
    path('registrar/',    views.registrarse,  name = 'registro'),
    path('recuperacion/', views.recuperar_pw, name = 'recuperacion'),
    path('logout/',       views.deslogearse,  name = 'logout'),

    #Predios
    path('predios/',                views.predios,          name = 'predios'),
    path('predios_deporte/',        views.predios_deporte,  name = 'predios_deporte'),
    path('filtrar_CanchaGaleria/',  views.filtrar_fotoslider,  name = 'filtrar_CanchaGaleria'),
    path('predio/<int:pk>/',        views.predio,           name = 'predio'),
    path('predio/edit/',            views.editar_predio,    name = 'editar_mipredio'),
    path('index',                   views.editar_user,      name = 'editar_user'),
    path('mi_predio/edit-cancha',   predio.editar_cancha,   name = 'editar_cancha'),
    path('mi_predio/estadisticas',  predio.stats,           name = 'estadisticas'),

    #Reservas
    path('mis_reservas/',               reservas.mis_reservas,     name = 'mis_reservas'),
    path('mis_reservas/cancel-reserva', reservas.cancelar_reserva, name = 'cancelar_reserva'),
    path('mi_predio/',                  reservas.mi_predio,        name = 'mi_predio'),
    path('crear_reserva/',              reservas.crear_reserva,    name = 'crear_reserva'),
    path('get_reserva/',                reservas.get_reserva,      name = 'get_reserva'),
    
    path('pre_reservar/',         reservas.pre_reservar,  name='pre_reservar'),
    path('esta_ocupado/',         reservas.esta_ocupado,  name='esta_ocupado'),

    #Cancha
    path('cancha/', views.cancha, name='cancha'),

    #mp
    path('obtener_links/', views.mercadopago_func, name='mercadopago_func'),
    path('retorno-pago/', views.retorno_pago, name='retorno_pago'),
    #path('notificacion-pago/', views.notificacion_pago, name='notificacion_pago'),

    path('envio/', email.send_mail_verificar, name='envio'),


]

scalo/scalo/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from reservas import estadisticas
from scalo.settings import base

urlpatterns = [
    path('', include('reservas.urls')),
    path('admin/', admin.site.urls),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

#if settings.DEBUG: SI ESTA EN DEBUG FALSE Y CON ESTE IF, NO RECUPERA LAS IMAGENES
#urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns +=static(base.STATIC_URL, document_root=base.STATIC_ROOT)
urlpatterns +=static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

admin.site.site_title = 'Messirve'
admin.site.site_header = 'Panel de Administración de Messirve'

scalo/reservas/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

class Deportes(models.Model):
    #Deporte_ID GENERADO POR DJANGO
    descripcion = models.CharField(db_column='Descripcion',max_length=40)

    class Meta:
        db_table            = 'deportes'
        ordering            = ['descripcion']
        verbose_name        = 'Deporte'
        verbose_name_plural = 'Deportes'

    def __str__(self) -> str:
        return self.descripcion
        #return super().__str__()

class Predios(models.Model):
    #Predio_ID GENERADO POR DJANGO
    user_id     = models.ForeignKey(User, models.PROTECT, db_column='user_id',verbose_name='User ID')
    nombre      = models.CharField (db_column='Nombre',max_length=50,null=False)
    direccion   = models.CharField (db_column='Direccion',max_length=250)
    logo        = models.ImageField(upload_to='upload/',db_column='Foto')#, null=True)#(db_column='Foto',max_length=250)
    lat         = models.FloatField(db_column='lat',blank=True,null=True)
    lng         = models.FloatField(db_column='lng',blank=True,null=True)
    telefono    = models.CharField(max_length=15, db_column='Telefono', blank=True, null=True)  
    email       = models.EmailField(max_length=100, db_column='Email', blank=True, null=True)
    descripcion = models.CharField(max_length=100, db_column='Desripcion', blank=True, null=True)
    link_mapa   = models.CharField(max_length=1000, db_column='link_mapa', blank=True, null=True)
    hora_ini    = models.CharField(max_length=20, db_column='hora_ini', blank=True, null=True)
    hora_fin    = models.CharField(max_length=20, db_column='hora_fin', blank=True, null=True)
    class Meta:
        db_table            = 'predios'
        ordering            = ['nombre']
        verbose_name        = 'Predio'
        verbose_name_plural = 'Predios'
    
    def __str__(self) -> str:
        # super().__str__()
        return self.nombre

class Canchas(models.Model):
    #Cancha_ID GENERADO POR DJANGO
    predio_id   = models.ForeignKey(Predios, models.PROTECT, db_column='predio_id',verbose_name='Predio ID')
    deporte_id  = models.ForeignKey(Deportes, models.PROTECT, db_column='deporte_id',verbose_name='Deporte ID')
    nombre      = models.CharField (db_column='Nombre',max_length=50,null=False)
    foto        = models.ImageField(upload_to='upload/',db_column='Foto')#, null=True)#(db_column='Foto',max_length=250)
    precio      = models.FloatField (db_column='Precio',default=0)#,null=True,blank=True)
    anticipo    = models.FloatField(db_column='Anticipo')#,blank=True,null=True)
    

    class Meta:
        db_table            = 'canchas'
        ordering            = ['nombre']
        verbose_name        = 'Cancha'
        verbose_name_plural = 'Canchas'
    
    def __str__(self) -> str:
        # super().__str__()
        return self.predio_id.nombre+' | '+ self.nombre

class Reservas(models.Model):

    ESTADO_RESERVA = (
        ('Cancelado', 'Cancelado'),
        ('Pendiente', 'Pendiente'),
        ('Activo', 'Activo'),
        #('No_Pago', 'No_Pago'),
        ('Si_jugo', 'Si_jugo'),
        ('No_jugo', 'No_jugo'),
    )

    #Reserva_ID GENERADO POR DJANGO
    user_id   = models.ForeignKey   (User, models.PROTECT, db_column='user_id',verbose_name='User ID')
    cancha_id = models.ForeignKey   (Canchas,models.PROTECT,db_column='cancha_id')
    fecha_ini = models.DateTimeField(db_column='Fecha_Ini',null=False,blank=False)
    fecha_fin = models.DateTimeField(db_column='Fecha_Fin',null=True,blank=True)
    precio    = models.FloatField (db_column='Precio')#,null=True,blank=True)#,blank=True,null=True)
    anticipo  = models.FloatField(db_column='Anticipo')#,blank=True,null=True)#,blank=True,null=True)
    estado    = models.CharField(db_column='estado',max_length=20,choices=ESTADO_RESERVA, default='Pendiente')
    fecha_creacion = models.DateTimeField(db_column='fecha_creacion',verbose_name="Fecha Creacion de Reserva",default=datetime.today())
    #idpago


    class Meta:
        db_table            = 'reservas'
        ordering            =['id']#,'reservas_id']
        verbose_name        = 'Reserva'
        verbose_name_plural = 'Reservas'
    
    def __str__(self) -> str:
        #return super().__str__()
        #return str(self.fecha_ini) + ' hasta ' + str(self.fecha_fin)
        return str(self.pk)

class Roles(models.Model):
    descripcion = models.CharField(db_column='Descripcion',max_length=40)

    class Meta:
        db_table            = 'roles'
        ordering            = ['descripcion']
        verbose_name        = 'Rol'
        verbose_name_plural = 'Roles'

    def __str__(self) -> str:
        return self.descripcion
        #return super().__str__()
        
class UsuarioXRoles(models.Model):
    user_id = models.ForeignKey(User,models.PROTECT,db_column='user_id',verbose_name='User ID')
    rol_id  = models.ForeignKey(Roles,models.PROTECT,db_column='rol_id',verbose_name='Rol')

    class Meta:
        db_table            = 'usuario_roles'
        ordering            = ['user_id']
        verbose_name        = 'Rol usuario'
        verbose_name_plural = 'Roles de usuarios'

    def __str__(self) -> str:
        #return super().__str__()
        return str(self.user_id)+ ' - '+str(self.rol_id)

class usuarios(models.Model):
    user_id = models.ForeignKey(User,models.PROTECT,db_column='user_id',verbose_name='User ID')
    fec_nac = models.DateField(db_column='fec_nac', verbose_name="Fecha de nacimiento")
    telef   = models.CharField(db_column='telefono',max_length=11,verbose_name="Teléfono")
    fecha_verificacion = models.DateField(db_column='fecha_verificacion',null=True, blank=True, default=None, verbose_name="Fecha de verificación")

    class Meta:
        db_table            = 'usuarios'
        ordering            = ['user_id']
        verbose_name        = 'Datos de usuario'
        verbose_name_plural = 'Datos de usuarios'

    def __str__(self) -> str:
        #return super().__str__()
        return str(self.user_id)

class pagos(models.Model):
    #id
    payment_id = models.CharField(max_length=25, db_column='payment_id', blank=True, null=True)  
    status  = models.CharField(max_length=15, db_column='status', blank=True, null=True)  
    monto = models.FloatField (db_column='monto')#,null=True,blank=True)
    reserva_id = models.ForeignKey(Reservas,models.PROTECT,db_column='reserva_id',)

    class Meta:
        db_table            = 'pagos'
        #ordering            = ['user_id']
        verbose_name        = 'Pago'
        verbose_name_plural = 'Pagos'

    def __str__(self) -> str:
        #return super().__str__()
        return str(self.payment_id)

scalo/reservas/templates/base.html
{% load static %}
{% load consulta_reservas %}
<!DOCTYPE html>
<html lang="es" class="smooth-scroll">

<head>
    <meta charset="UTF-8">
    <title>Reserva Total</title>
    <link rel="shortcut icon" href="{% static 'img/logo-color.ico' %}" type="image/x-icon">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
{% block css %}
{% endblock %}

<body>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success' %}
    <script>
        const Toast = Swal.mixin({
            toast: true,
            position: 'top-right',
            iconColor: 'white',
            width: 500,
            customClass: {
                popup: 'colored-toast'
            },
            showConfirmButton: false,
            timer: 3500,
            timerProgressBar: true
        })
        Toast.fire({
            icon: 'success',
            title: '{{ message|safe }}'
        })
    </script>
    {% else %}
    <script>
        Toast.fire({
            icon: 'error',
            title: '{{ message|safe }}'
        })
    </script>
    {% endif %}
    {% endfor %}
    {% endif %}

    {% if 'https://softwarecancha.onrender.com/' == request.build_absolute_uri or '5inco.online' == request.build_absolute_uri %}
    <header>
        {% else %}
        <header class="absolute">
            {% endif %}

            <!-- <a href="{% url 'predios' %}">Predios</a> -->

            <!-- <nav class="navbar navbar-expand-lg px-4">
                <div class="container-fluid">
                    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                        <ul class="navbar-nav">
                            {% if user.is_authenticated %}
                            {% if perms.reservas.view_reservas %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'mis_reservas' %}">Mis reservas</a>
                            </li>
                            {% endif %}
                            {% if perms.reservas.change_predios %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'mi_predio' %}">Mi predio</a>
                            </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link inises" href="{% url 'logout' %}">Salir</a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'registro' %}">Registrarse</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link inises" href="{% url 'login' %}">Iniciar Sesión</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav> -->
            <nav class="navbar px-4">
                <div class="container-fluid">
                    <h1><a class="navbar-brand" href="{% url 'index' %}"><img
                                src="{% static 'img/logo-no-background.png' %}" alt="Reserva Total"></a></h1>
                    {% if user.is_authenticated %}
                    <div class="d-flex gap-4 px-1 align-items-center">
                        <div>
                            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                                data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"
                                aria-label="Toggle navigation">
                                <h5 class="offcanvas-title" style="font-size: 1.25rem;" id="offcanvasNavbarLabel">
                                    {{user.first_name}}</h5>
                            </button>
                        </div>
                        <svg xmlns="http://www.w3.org/2000/svg" type="button" width="50" height="50" fill="currentColor" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation" 
                            class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                            <path fill-rule="evenodd"
                                d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                        </svg>
                    </div>
                    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
                        aria-labelledby="offcanvasNavbarLabel">
                        <div class="offcanvas-header">
                            <div class="d-flex gap-4 px-1">
                                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor"
                                    class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                                    <path fill-rule="evenodd"
                                        d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                                </svg>
                                <div>
                                    <h5 class="offcanvas-title" style="font-size: 1.25rem;" id="offcanvasNavbarLabel">
                                        {{user.first_name}}</h5>
                                    <h4 class="" style="font-size: .875rem;" id="offcanvasNavbarLabel">{{user.email}}
                                    </h4>
                                </div>
                            </div>
                            <button type="button" class="btn-close" style="background-color: #ABF7F7;"
                                data-bs-dismiss="offcanvas" aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body">
                            <ul class="navbar-nav">
                                {% if perms.reservas.view_reservas %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'mis_reservas' %}">Mis reservas</a>
                                </li>
                                {% endif %}
                                {% if perms.reservas.change_predios %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'mi_predio' %}">Mi predio</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'estadisticas' %}">Estadisticas</a>
                                </li>
                                {% endif %}
                                <li class="nav-item">
                                    <a class="nav-link" style="cursor: pointer;"
                                        onclick="ModalEditarUser('{{ cancha.id }}')">
                                        Modificar datos personales
                                    </a>
                                </li>
                                <hr>
                                <li class="nav-item">
                                    <a class="nav-link lout" href="{% url 'logout' %}">Salir</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    {% else %}
                    <div class="d-flex justify-content-end" id="navbarNav">
                        <ul class="navbar-nav d-flex flex-row">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'registro' %}">Registrarse</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link inises" href="{% url 'login' %}">Iniciar Sesión</a>
                            </li>
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </nav>
        </header>

        <!-- Modal PARA EDITAR USUARIO -->
        <div class="modal fade " id="modaleditaruser" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">Modificando datos personales</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form method="post" action="{% url 'editar_user' %}">
                        {% csrf_token %}

                        <div class="modal-body">


                            <div class="form-group">
                                <label for="nombre">Nombre</label>
                                <input type="text" class="form-control " id="nombre" name="nombre"
                                    value="{{ user.first_name }}">
                            </div>

                            <div class="form-group">
                                <label for="apellido">Apellido</label>
                                <input type="text" class="form-control" name="apellido" id="apellido"
                                    aria-describedby="predioHelp" value="{{ user.last_name }}">
                            </div>


                            <div class="form-group">
                                <label for="telefono_user">Teléfono:</label>
                                {% if user.is_authenticated %}
                                <input type="text" class="form-control" name="telefono_user" id="telefono_user"
                                    aria-describedby="predioHelp" value="{% get_telefono user.id %}">
                                {% endif %}
                            </div>
                            <input type="hidden" class="form-control" name="user_id" id="user_id" value="{{user.id}}">
                            <div class="form-group">
                                <label for="email_user">Email</label>
                                <input type="email" class="form-control" id="email_user" name="email_user"
                                    aria-describedby="emailHelp" value="{{ user.email }}">
                            </div>

                        </div>
                        <div class="modal-footer">
                            <a type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</a>
                            <button type="submit" class="btn btn-primary">Confirmar cambios</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>

        {% block content %}
        {% endblock %}

        <footer>
            <div class="footer-logo">
                <a href=""><img
                        src="{% static 'img/reserva-total-low-resolution-logo-white-on-transparent-background.png' %}"
                        alt="Logo Footer"></a>
                <p>Copyright @ 2023 Reserva Total</p>
            </div>

            <div class="footer-redes-sociales">
                <a href="{% url 'index' %}"><img src="{% static 'img/item-fb.png' %}" alt="wpp"></a>
                <a href="{% url 'index' %}"><img src="{% static 'img/item-ig.png' %}" alt="insta"></a>
            </div>

            <div class="footer-predios">
                <h4>PREDIOS</h4>
                <ul>
                    <li>Predio 1</li>
                    <li>Predio 2</li>
                    <li>Predio 3</li>
                </ul>
            </div>

            <div class="footer-info-contacto">
                <div>
                    <img src="{% static 'img/Phone.png' %}" alt="Icono Telefono">
                    <p>387 1111-111</p>
                </div>
                <div>
                    <img src="{% static 'img/Vector.png' %}" alt="Icono Ubicacion">
                    <p>Salta, Argentina</p>
                </div>
                <div>
                    <img src="{% static 'img/mail.png' %}" alt="Icono Mail">
                    <p>info@reservatotal.com.ar</p>
                </div>
            </div>
        </footer>

        <script>
            function ModalEditarUser(user_id) {

                $('#modaleditaruser').modal('show')
            }
        </script>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
        {% block javascript %}
        {% endblock %}
</body>

</html>

scalo/reservas/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Reserva Total</title>
    <link rel="shortcut icon" href="{% static 'img/logo-color.ico' %}" type="image/x-icon">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
{% block css %}
{% endblock %}

    <body>
        <!-- <header>
            <a href="{% url 'predios' %}">Predios</a>

            <nav class="navbar navbar-expand-lg px-4">
                <div class="container-fluid">
                    <h1><a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'img/logo-no-background.png' %}"
                                alt="Reserva Total"></a></h1>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                        <ul class="navbar-nav">
                            {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link inises" href="{% url 'logout' %}">Salir</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'registro' %}">Registrarse</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link inises" href="{% url 'login' %}">Iniciar Sesión</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </header> -->

        {% block content %}
        {% endblock %}

        <!-- <footer>
            <div class="footer-logo">
                <a href=""><img src="{% static 'img/reserva-total-low-resolution-logo-white-on-transparent-background.png' %}" alt="Logo Footer"></a>
                <p>Copyright @ 2023 Reserva Total</p>
            </div>
    
            <div class="footer-redes-sociales">
                <a href="{% url 'index' %}"><img src="{% static 'img/item-fb.png' %}" alt="wpp"></a>
                <a href="{% url 'index' %}"><img src="{% static 'img/item-ig.png' %}" alt="insta"></a>
            </div>
            
            <div class="footer-predios">
                <h4>PREDIOS</h4>        
                <ul>
                    <li>Predio 1</li>
                    <li>Predio 2</li>
                    <li>Predio 3</li>
                </ul>
            </div>
            
            <div class="footer-info-contacto">
                <div>
                    <img src="{% static 'img/Phone.png' %}" alt="Icono Telefono">
                    <p>387 1111-111</p>
                </div>
                <div>
                    <img src="{% static 'img/Vector.png' %}" alt="Icono Ubicacion">
                    <p>Salta, Argentina</p>
                </div>
                <div>
                    <img src="{% static 'img/mail.png' %}" alt="Icono Mail">
                    <p>info@reservatotal.com.ar</p>
                </div>
            </div>
        </footer> -->

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    </body>

</html>

scalo/reservas/templates/estadisticas.html
{% extends 'base.html' %}
{% load static %}
{% load plotly_dash %}

{% block content %}
{% plotly_header %}
<div class="container" style="height: fit-content; width: 100%; justify-content: space-between; max-width: 100%;">
    {%plotly_direct name='dash_example' %}
</div>
{% plotly_footer %}
{% endblock %}

scalo/reservas/templates/index.html
{% extends 'base.html' %}

{% block content %}

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<!-- {% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                </symbol>
            </svg>
            <div class="alert alert-success d-flex align-items-center alert-dismissible fade show" role="alert" style="position: fixed; width: 100%;"><svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg> 
                {{ message|safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% else %}
            <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </symbol>
            </svg>
            <div class="alert alert-danger d-flex align-items-center alert-dismissible fade show" role="alert" style="position: fixed; width: 100%;"><svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                {{ message|safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
    {% endfor %}
{% endif %} -->
<section class="bienvenida">
    <h2>Encuentra, <strong>Reserva</strong>, Juega: <br> Bienvenido a Nuestro Mundo Deportivo.</h2>
    <p>Nuestro sistema de gestión de turnos te ofrece la libertad de reservar canchas para una variedad de deportes en cualquier momento, permitiéndote enfocarte en lo que más te apasiona: jugar.</p>
    <button><a href="{% url 'predios' %}">Explorar predios</a></button>
</section>
{% endblock %}

scalo/reservas/templates/prueba.html
<h1>hola</h1>